/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("application")
    id("maven-publish")
    id("checkstyle")
    alias(libs.plugins.shadow)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // The upload destination
    maven { url = uri("https://codeberg.org/api/packages/haruki7049/maven") }
}

dependencies {
    implementation(project(":buildente-lib"))
    implementation(libs.picocli)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    withJavadocJar()
    withSourcesJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "dev.haruki7049.buildente.Main"
}

publishing {
    repositories {
        maven {
            name = "Codeberg"
            url = uri("https://codeberg.org/api/packages/haruki7049/maven")

            credentials {
                username = System.getenv("CODEBERG_USERNAME") ?: ""
                password = System.getenv("CODEBERG_TOKEN") ?: ""
            }
        }
    }

    publications {
        create<MavenPublication>("maven") {
            groupId = "dev.haruki7049.buildente"
            artifactId = "buildente-app"
            version = System.getenv("BUILDENTE_VERSION") ?: "main-local"

            from(components["shadow"])

            pom {
                url = "https://codeberg.org/haruki7049/buildente"
                scm {
                    url = "https://codeberg.org/haruki7049/buildente"
                    connection = "scm:git:https://codeberg.org/haruki7049/buildente.git"
                    developerConnection = "scm:git:ssh://codeberg.org/haruki7049/buildente.git"
                }
            }
        }
    }
}

checkstyle {
    toolVersion = "12.1.1"
}
